# Generated by Django 5.0.3 on 2024-03-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='handbookentry',
            unique_together={('category', 'slug')},
        ),
    ]
